-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK b
INNER JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
INNER JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE DATE_FORMAT(bs.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY b.CATEGORY, a.AUTHOR_NAME
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;