-- 코드를 입력하세요
SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') as SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
FROM ONLINE_SALE N
WHERE N.SALES_DATE LIKE '2022-03%'
UNION
SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d') as SALES_DATE, F.PRODUCT_ID, NULL as USER_ID, F.SALES_AMOUNT
FROM OFFLINE_SALE F
WHERE F.SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC